### ISSUE TITLE
default Controller is not work

### ISSUE THREAD

**Issue by huiralb** [panada/app#2]
Hallo, pada <code>src/config/main.php</code> saya atur default controller

``` php
'defaultController' => 'Pages'
```

kemudian saya akses <code>http://localhost:8181</code> tetapi yang bekerja tetap <code>Home Controller</code>
Jika saya akses <code>http://localhost:8181/pages</code> ini bekerja.

Adakah pengaturan yang lain?

**Comment by ikandars** [comment]
Oke dicek dulu ya 
On Nov 11, 2015 10:13 PM, Husain Irnovi Albaweny notifications@github.com wrote:Hallo, pada src/config/main.php saya atur default controller

'defaultController' => 'Pages'

kemudian saya akses http://localhost:8181 tetapi yang bekerja tetap Home Controller
Jika saya akses http://localhost:8181/pages ini bekerja.

Adakah pengaturan yang lain?

**Comment by ikandars** [comment]
Yang ini sudah difix ya. Kalau install pake composer silahkan jalankan composer update aja.

thx
